/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ngx-croppie.component';
const styles_NgxCroppieComponent:any[] = ([] as any[]);
export const RenderType_NgxCroppieComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NgxCroppieComponent,data:{}});
export function View_NgxCroppieComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{imageEdit:0}),(_l()(),i0.ɵeld(0,[[1,0],['imageEdit',
      1]],(null as any),0,'div',([] as any[]),(null as any),[[(null as any),'update']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.NgxCroppieComponent = _v.component;
        if (('update' === en)) {
          const pd_0:any = ((<any>_co.newResult()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any)))],(null as any),(null as any));
}
export function View_NgxCroppieComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ngx-croppie',
      ([] as any[]),(null as any),(null as any),(null as any),View_NgxCroppieComponent_0,
      RenderType_NgxCroppieComponent)),i0.ɵdid(114688,(null as any),0,i1.NgxCroppieComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NgxCroppieComponentNgFactory:i0.ComponentFactory<i1.NgxCroppieComponent> = i0.ɵccf('ngx-croppie',
    i1.NgxCroppieComponent,View_NgxCroppieComponent_Host_0,{croppieOptions:'croppieOptions',
        imageUrl:'imageUrl',bind:'bind',outputFormatOptions:'outputFormatOptions'},
    {result:'result'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2x1a2Fzc2Nob25iYWNobGVyL0Rvd25sb2Fkcy9uZ3gtY3JvcHBpZS9zcmMvbmd4LWNyb3BwaWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2x1a2Fzc2Nob25iYWNobGVyL0Rvd25sb2Fkcy9uZ3gtY3JvcHBpZS9zcmMvbmd4LWNyb3BwaWUuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvbHVrYXNzY2hvbmJhY2hsZXIvRG93bmxvYWRzL25neC1jcm9wcGllL3NyYy9uZ3gtY3JvcHBpZS5jb21wb25lbnQudHMuTmd4Q3JvcHBpZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvbHVrYXNzY2hvbmJhY2hsZXIvRG93bmxvYWRzL25neC1jcm9wcGllL3NyYy9uZ3gtY3JvcHBpZS5jb21wb25lbnQudHMuTmd4Q3JvcHBpZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgI2ltYWdlRWRpdCAodXBkYXRlKT1cIm5ld1Jlc3VsdCgpXCI+PC9kaXY+IiwiPG5neC1jcm9wcGllPjwvbmd4LWNyb3BwaWU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7dURDQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFnQjtVQUFBO1VBQUE7UUFBQTtRQUFoQjtNQUFBOzs7b0JDQUE7TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBQTs7Ozs7OyJ9
